openapi: 3.0.0
info:
  title: Auction API
  description: API for auction
  version: 1.0.0
tags:
  - name: user
    description: Operations about user
  - name: lots
    description: Access to lots list
  - name: admin
    description: Access to lots list
paths:
  /users/register:
    post:
      tags:
        - user
      summary: register
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                login:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: register successfully

  /users/{userId}/won_lots:
    get:
      tags:
        - user
      summary: lots won
      parameters:
        - name: userId
          in: path
          required: true
          description: user id
          schema:
            type: string
      responses:
        '200':
          description: succesfully
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lot'

  /admin/add_lot:
    post:
      tags:
        - admin
      summary: Add new lot (admin)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LotCreate'
              type: object
              properties:
                name:
                  type: string
                  description: Lot name
                initial_price:
                  type: number
                  description: Started coast
                image:
                  type: string
                  format: uri
                  description: url image
                duration:
                  type: integer
                  description: duration of lot
      responses:
        '201':
          description: lot added

  /admin/delete_lot/{lotId}:
    delete:
      tags:
        - admin
      summary: Delete lot (admin)
      parameters:
        - name: lotId
          in: path
          required: true
          description: lot ID
          schema:
            type: string
      responses:
        '204':
          description: lot delete
          
  /admin/status/{lotId}:
    patch:
      tags:
        - admin
      summary: Update lot status (admin)
      parameters:
        - name: lotId
          in: path
          required: true
          description: lot id
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                isActive:
                  type: boolean
                  description: Lot status has been changed
      responses:
        '204':
          description: Lot activity has been successfully updated
        # Другие возможные коды ответов
  
  /lots/{lotId}:
    get:
      tags:
        - lots
      summary: Lots ID
      parameters:
        - name: lotId
          in: path
          required: true
          description: lot ID
          schema:
            type: string
      responses:
        '200':
          description: lot {id}
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Lot'

  /lots:
    get:
      tags:
        - lots
      summary: List of a lots
      responses:
        '200':
          description: list of a lots
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lot'

components:
  schemas:
    User:
      type: object
      properties:
        login:
          type: string
        password:
          type: string

    Lot:
      type: object
      properties:
        name:
          type: string
          description: name of lot
        initial_price:
          type: number
          description: started cost
        image:
          type: string
          format: uri
          description: url image
        duration:
          type: integer
          description: duration lot
          
    Admin:
      type: object
      properties:
        lotstatus:
          type: string
          description: status of a lot
          
    LotCreate:
      type: object
      properties:
        title:
          type: string
        description:
          type: string
        duration:
          type: integer

